# Generated by Django 4.1.5 on 2023-01-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_feedbackparents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeedBackParents',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
